# terminal-autocorrect PowerShell hook
# Generated by: tac init powershell
# 
# INSTALLATION: Copy this file somewhere permanent, then add this line to your $PROFILE:
#   . "C:\path\to\tac-hook.ps1"
#
# Or copy the contents directly into your $PROFILE.

function _TacSend {
  param([string]$Type, [string]$Buffer)
  
  # Prevent recursion: skip if we're already inside the hook
  if ($global:_TacInHook) { return $null }
  
  try {
    $global:_TacInHook = $true
    $result = & tac --ipc $Type --buffer $Buffer 2>$null
    if ($result -is [array]) { return ($result -join '') }
    return $result
  } catch {
    return $null
  } finally {
    $global:_TacInHook = $false
  }
}

# Initialize guard variable and suggestion state
$global:_TacInHook = $false
$global:_TacCurrentSuggestion = $null
$global:_TacSuggestionShown = $false

# Paste detection state
# _TacPasting: set by Ctrl+V handler, cleared after cooldown
# _TacLastInputTime: epoch-ms of last character insertion (burst detection)
# _TacPasteModeUntil: epoch-ms until which paste/burst mode is active
$global:_TacPasting = $false
$global:_TacLastInputTime = [long]0
$global:_TacPasteModeUntil = [long]0

function _TacIsInPasteMode {
  # Returns $true when we should suppress autocorrect/suggestions.
  # Covers: Ctrl+V flag, burst detection (chars arriving < 8 ms apart).
  $now = [System.DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
  $timeSinceLast = $now - $global:_TacLastInputTime
  if ($timeSinceLast -lt 8) {
    # Characters arriving very fast ΓÇö treat as paste burst, extend cooldown
    $global:_TacPasteModeUntil = $now + 300
  }
  $global:_TacLastInputTime = $now
  return ($global:_TacPasting -or ($now -lt $global:_TacPasteModeUntil))
}

function _TacClearGhostText {
  if ($global:_TacSuggestionShown) {
    $line = $null; $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    $actualInput = if ($line.Length -gt 0) { $line.Substring(0, $cursor) } else { "" }
    if ($line.Length -gt 0) {
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actualInput)
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($actualInput.Length)
    }
    $global:_TacSuggestionShown = $false
    $global:_TacCurrentSuggestion = $null
  }
}

# Autocorrect: Use PSReadLine to intercept the full command line before execution
if (Get-Module -ListAvailable -Name PSReadLine) {
  Set-PSReadLineKeyHandler -Key Enter -ScriptBlock {
    $line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    
    if ($line -and $line.Trim()) {
      # Learn from this command before correction
      $originalCommand = $line.Trim()
      
      # Send the ENTIRE command line to the daemon for correction
      $corrected = _TacSend -Type 'correct' -Buffer $line.Trim()
      
      if ($corrected -and $corrected -ne $line.Trim() -and $corrected.Trim()) {
        # Replace the entire line with the corrected version
        [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $corrected)
        Write-Host "`nAutocorrected: $($line.Trim()) -> $corrected" -ForegroundColor Green
        
        # Learn from the corrected command
        Learn-TypingPattern -Command $corrected

      } else {
        # Learn from the original command (no correction needed)
        Learn-TypingPattern -Command $originalCommand
      }
    }
    
    # Clear any suggestion state
    $global:_TacCurrentSuggestion = $null
    $global:_TacSuggestionShown = $false
    
    # Execute the command
    [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
  }

  # Real-time suggestions as you type - automatic like VS Code IntelliSense
  # We'll use a more sophisticated approach with PSReadLine's character handlers
  
  # Function to learn from typing patterns
  function Learn-TypingPattern {
    param([string]$Command)
    
    if ($Command -and $Command.Length -gt 2) {
      # Learn prefixes for this command
      for ($i = 1; $i -lt $Command.Length; $i++) {
        $prefix = $Command.Substring(0, $i)
        if ($prefix.Length -ge 1) {
          # Send learning request to daemon
          & tac --ipc learn --prefix $prefix --completion $Command 2>$null | Out-Null
        }
      }
    }
  }

  # Function to update suggestions in real-time
  function Update-TacSuggestion {
    $line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    
    # Get the actual user input (everything before cursor)
    $actualInput = if ($line.Length -gt 0) { $line.Substring(0, $cursor) } else { "" }
    
    if ($actualInput -and $actualInput.Trim().Length -gt 0) {
      $suggestion = _TacSend -Type 'suggest' -Buffer $actualInput.Trim()
      
      if ($suggestion -and $suggestion -ne $actualInput.Trim() -and $suggestion.StartsWith($actualInput.Trim())) {
        # Calculate the ghost text (what comes after current input)
        $ghostText = $suggestion.Substring($actualInput.Trim().Length)
        
        if ($ghostText) {
          # Replace entire line with actual input + ghost text
          if ($line.Length -gt 0) {
            [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actualInput + $ghostText)
          } else {
            [Microsoft.PowerShell.PSConsoleReadLine]::Insert($actualInput + $ghostText)
          }
          
          # Set cursor back to end of actual input
          [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($actualInput.Length)
          
          $global:_TacCurrentSuggestion = $suggestion
          $global:_TacSuggestionShown = $true
          return
        }
      }
    }
    
    # No suggestion available - clear any existing ghost text
    if ($global:_TacSuggestionShown) {
      if ($line.Length -gt 0) {
        [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actualInput)
      }
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($actualInput.Length)
    }
    
    $global:_TacCurrentSuggestion = $null
    $global:_TacSuggestionShown = $false
  }
  
  # Hook into all printable characters to show suggestions as you type
  # This creates real-time IntelliSense-like behavior
  for ($i = 32; $i -le 126; $i++) {
    $char = [char]$i
    if ($char -match '[a-zA-Z0-9\-\._/\\]') {  # Only hook alphanumeric and common symbols
      Set-PSReadLineKeyHandler -Chord $char -ScriptBlock {
        param($key, $arg)
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert($key.KeyChar)
        if (-not (_TacIsInPasteMode)) {
          Update-TacSuggestion
        }
      }.GetNewClosure()
    }
  }
  
  # Also hook space for command completion
  Set-PSReadLineKeyHandler -Chord ' ' -ScriptBlock {
    [Microsoft.PowerShell.PSConsoleReadLine]::Insert(' ')
    if (-not (_TacIsInPasteMode)) {
      Update-TacSuggestion
    }
  }

  # Ctrl+V paste ΓÇö clear ghost text, enter paste mode, do the paste, exit after 300ms
  Set-PSReadLineKeyHandler -Chord 'Ctrl+v' -ScriptBlock {
    _TacClearGhostText
    $global:_TacPasting = $true
    $global:_TacPasteModeUntil = [System.DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds() + 300
    [Microsoft.PowerShell.PSConsoleReadLine]::Paste()
    $null = [System.Threading.Tasks.Task]::Run({
      Start-Sleep -Milliseconds 300
      $global:_TacPasting = $false
    })
  }
  
  # Hook backspace to update suggestions when deleting
  Set-PSReadLineKeyHandler -Key Backspace -ScriptBlock {
    if ($global:_TacSuggestionShown) {
      $line = $null
      $cursor = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
      $actualInput = $line.Substring(0, $cursor)
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actualInput)
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($cursor)
      $global:_TacSuggestionShown = $false
    }
    [Microsoft.PowerShell.PSConsoleReadLine]::BackwardDeleteChar()
    if (-not (_TacIsInPasteMode)) {
      Update-TacSuggestion
    }
  }

  # Tab key to accept suggestion
  Set-PSReadLineKeyHandler -Key Tab -ScriptBlock {
    if ($global:_TacCurrentSuggestion -and $global:_TacSuggestionShown) {
      try {
        # Accept the suggestion - replace entire line properly
        $line = $null
        $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        
        # Replace with the full suggestion
        if ($line.Length -gt 0) {
          [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $global:_TacCurrentSuggestion)
        } else {
          [Microsoft.PowerShell.PSConsoleReadLine]::Insert($global:_TacCurrentSuggestion)
        }
        
        # Clear suggestion state
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown = $false
      } catch {
        # If there's an error, just clear the state and do default tab
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown = $false
        [Microsoft.PowerShell.PSConsoleReadLine]::TabCompleteNext()
      }
    } else {
      # Default tab behavior (completion)
      [Microsoft.PowerShell.PSConsoleReadLine]::TabCompleteNext()
    }
  }

  # Right arrow to accept suggestion (like VS Code)
  Set-PSReadLineKeyHandler -Key RightArrow -ScriptBlock {
    if ($global:_TacCurrentSuggestion -and $global:_TacSuggestionShown) {
      try {
        # Accept the suggestion - replace entire line properly
        $line = $null
        $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        
        # Replace with the full suggestion
        if ($line.Length -gt 0) {
          [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $global:_TacCurrentSuggestion)
        } else {
          [Microsoft.PowerShell.PSConsoleReadLine]::Insert($global:_TacCurrentSuggestion)
        }
        
        # Clear suggestion state
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown = $false
      } catch {
        # If there's an error, just clear the state and do default right arrow
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown = $false
        [Microsoft.PowerShell.PSConsoleReadLine]::ForwardChar()
      }
    } else {
      # Default right arrow behavior
      [Microsoft.PowerShell.PSConsoleReadLine]::ForwardChar()
    }
  }

  # Escape to dismiss suggestion
  Set-PSReadLineKeyHandler -Key Escape -ScriptBlock {
    if ($global:_TacSuggestionShown) {
      try {
        # Clear the suggestion by replacing with just the actual input
        $line = $null
        $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        $actualInput = $line.Substring(0, $cursor)
        if ($line.Length -gt 0) {
          [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actualInput)
        }
        [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($actualInput.Length)
        
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown = $false
      } catch {
        # If there's an error, just clear the state
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown = $false
      }
    } else {
      # Default escape behavior
      [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
    }
  }

  # Delete key also updates suggestions
  Set-PSReadLineKeyHandler -Key Delete -ScriptBlock {
    if ($global:_TacSuggestionShown) {
      $line = $null
      $cursor = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
      $actualInput = $line.Substring(0, $cursor)
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actualInput)
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($cursor)
      $global:_TacSuggestionShown = $false
    }
    [Microsoft.PowerShell.PSConsoleReadLine]::DeleteChar()
    if (-not (_TacIsInPasteMode)) {
      Update-TacSuggestion
    }
  }
}

# Record executed commands in prompt (simplified for speed)
$null = New-Variable -Name _TacOriginalPrompt -Value (Get-Item Function:\prompt -ErrorAction SilentlyContinue).ScriptBlock -Scope Global -Force -ErrorAction SilentlyContinue
function global:prompt {
  # Record history without blocking
  $lastId = (Get-History -Count 1 -ErrorAction SilentlyContinue).Id
  if ($null -ne $lastId -and $lastId -ne $global:_TacLastRecordedId) {
    $global:_TacLastRecordedId = $lastId
    $lastCmd = (Get-History -Id $lastId -ErrorAction SilentlyContinue).CommandLine
    if ($lastCmd) { 
      # Record in background
      Start-Job -ScriptBlock { 
        param($cmd) 
        & tac --ipc record --buffer $cmd 2>$null 
      } -ArgumentList $lastCmd | Out-Null
    }
  }
  
  # Call original prompt
  if ($null -ne $global:_TacOriginalPrompt) {
    & $global:_TacOriginalPrompt
  } else {
    "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
  }
}
