# terminal-autocorrect PowerShell hook
# Generated by: tac init powershell
# 
# INSTALLATION: Copy this file somewhere permanent, then add this line to your $PROFILE:
#   . "C:\path\to\tac-hook.ps1"
#
# Or copy the contents directly into your $PROFILE.

function _TacSend {
  param([string]$Type, [string]$Buffer)
  
  # Prevent recursion: skip if we're already inside the hook
  if ($global:_TacInHook) { return $null }
  
  try {
    $global:_TacInHook = $true
    $result = & tac --ipc $Type --buffer $Buffer 2>$null
    if ($result -is [array]) { return ($result -join '') }
    return $result
  } catch {
    return $null
  } finally {
    $global:_TacInHook = $false
  }
}

# Initialize guard variable
$global:_TacInHook = $false

# Autocorrect: Use PSReadLine to intercept the full command line before execution
# This works for all commands, including external executables like git, npm, etc.
if (Get-Module -ListAvailable -Name PSReadLine) {
  Set-PSReadLineKeyHandler -Key Enter -ScriptBlock {
    $line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    
    if ($line) {
      # Extract the first word (command name) from the line
      $firstWord = ($line -split '\s+')[0]
      if ($firstWord) {
        $corrected = _TacSend -Type 'correct' -Buffer $firstWord
        if ($corrected -and $corrected -ne $firstWord) {
          # Replace the first word with the corrected version
          $newLine = $line -replace "^$([regex]::Escape($firstWord))", $corrected
          [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $newLine)
          Write-Host "`n`u{2713} autocorrected: $firstWord -> $corrected" -ForegroundColor Green
        }
      }
    }
    
    # Execute the command
    [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
  }
}

# Record executed commands + show next-command prediction via prompt hook
$null = New-Variable -Name _TacOriginalPrompt -Value (Get-Item Function:\prompt -ErrorAction SilentlyContinue).ScriptBlock -Scope Global -Force -ErrorAction SilentlyContinue
function global:prompt {
  $lastId = (Get-History -Count 1 -ErrorAction SilentlyContinue).Id
  if ($null -ne $lastId -and $lastId -ne $global:_TacLastRecordedId) {
    $global:_TacLastRecordedId = $lastId
    $lastCmd = (Get-History -Id $lastId -ErrorAction SilentlyContinue).CommandLine
    if ($lastCmd) { _TacSend -Type 'record' -Buffer $lastCmd | Out-Null }
  }
  $prediction = _TacSend -Type 'suggest' -Buffer ''
  if ($prediction) { Write-Host "  hint: $prediction" -ForegroundColor DarkGray }
  if ($null -ne $global:_TacOriginalPrompt) {
    & $global:_TacOriginalPrompt
  } else {
    "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
  }
}
