# terminal-autocorrect PowerShell hook
# Generated by: tac init powershell
#
# INSTALLATION: Add this line to your $PROFILE:
#   . "C:\path\to\tac-hook.ps1"

function _TacSend {
  param([string]$Type, [string]$Buffer)
  if ($global:_TacInHook) { return $null }
  try {
    $global:_TacInHook = $true
    $result = & tac --ipc $Type --buffer $Buffer 2>$null
    if ($result -is [array]) { return ($result -join '') }
    return $result
  } catch {
    return $null
  } finally {
    $global:_TacInHook = $false
  }
}

# ── State ──────────────────────────────────────────────────────────────────
$global:_TacInHook            = $false
$global:_TacCurrentSuggestion = $null
$global:_TacSuggestionShown   = $false

# Debounce: track when the last key was pressed (epoch-ms)
# Suggestion only fires if the NEXT key arrives >= 300ms after the previous one
$global:_TacLastKeyMs         = [long]0
$global:_TacDebounceMs        = 300

# Paste burst: if keys arrive < 8ms apart, suppress suggestions for 300ms
$global:_TacPasteModeUntilMs  = [long]0

# ── Helpers ────────────────────────────────────────────────────────────────

function _TacOnKey {
  # Call FIRST in every character handler.
  # Returns: "paste" | "debounce" | "suggest"
  #   paste    = burst input, skip everything
  #   debounce = typed too recently, skip suggestion but don't clear
  #   suggest  = paused long enough, show suggestion
  $now = [System.DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
  $gap = $now - $global:_TacLastKeyMs
  $global:_TacLastKeyMs = $now

  # Burst detection: < 8ms between keys = paste
  if ($gap -ge 0 -and $gap -lt 8) {
    $global:_TacPasteModeUntilMs = $now + 300
  }
  if ($now -lt $global:_TacPasteModeUntilMs) {
    return "paste"
  }

  # Debounce: typed within 300ms of last key = wait
  if ($gap -lt $global:_TacDebounceMs) {
    return "debounce"
  }

  return "suggest"
}

function _TacClearGhostText {
  if ($global:_TacSuggestionShown) {
    $line = $null; $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    $actual = if ($line.Length -gt 0) { $line.Substring(0, $cursor) } else { "" }
    if ($line.Length -gt 0) {
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actual)
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($actual.Length)
    }
    $global:_TacSuggestionShown   = $false
    $global:_TacCurrentSuggestion = $null
  }
}

function Update-TacSuggestion {
  $line = $null; $cursor = $null
  [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
  $actual = if ($line.Length -gt 0) { $line.Substring(0, $cursor) } else { "" }

  if ($actual -and $actual.Trim().Length -gt 0) {
    $suggestion = _TacSend -Type 'suggest' -Buffer $actual.Trim()
    if ($suggestion -and
        $suggestion -ne $actual.Trim() -and
        $suggestion.StartsWith($actual.Trim())) {
      $ghost = $suggestion.Substring($actual.Trim().Length)
      if ($ghost) {
        if ($line.Length -gt 0) {
          [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actual + $ghost)
        } else {
          [Microsoft.PowerShell.PSConsoleReadLine]::Insert($actual + $ghost)
        }
        [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($actual.Length)
        $global:_TacCurrentSuggestion = $suggestion
        $global:_TacSuggestionShown   = $true
        return
      }
    }
  }

  # No suggestion — clear ghost text if shown
  if ($global:_TacSuggestionShown) {
    $line2 = $null; $cur2 = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line2, [ref]$cur2)
    $actual2 = if ($line2.Length -gt 0) { $line2.Substring(0, $cur2) } else { "" }
    if ($line2.Length -gt 0) {
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line2.Length, $actual2)
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($actual2.Length)
    }
  }
  $global:_TacCurrentSuggestion = $null
  $global:_TacSuggestionShown   = $false
}

function Learn-TypingPattern {
  param([string]$Command)
  if ($Command -and $Command.Length -gt 2) {
    for ($i = 1; $i -lt $Command.Length; $i++) {
      $prefix = $Command.Substring(0, $i)
      & tac --ipc learn --prefix $prefix --completion $Command 2>$null | Out-Null
    }
  }
}

# ── PSReadLine hooks ───────────────────────────────────────────────────────

if (Get-Module -ListAvailable -Name PSReadLine) {

  # Enter: autocorrect then execute
  Set-PSReadLineKeyHandler -Key Enter -ScriptBlock {
    _TacClearGhostText
    $line = $null; $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    if ($line -and $line.Trim()) {
      $orig      = $line.Trim()
      $corrected = _TacSend -Type 'correct' -Buffer $orig
      if ($corrected -and $corrected -ne $orig -and $corrected.Trim()) {
        [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $corrected)
        Write-Host "`nAutocorrected: $orig -> $corrected" -ForegroundColor Green
        Learn-TypingPattern -Command $corrected
      } else {
        Learn-TypingPattern -Command $orig
      }
    }
    $global:_TacCurrentSuggestion = $null
    $global:_TacSuggestionShown   = $false
    [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
  }

  # Printable characters
  # _TacOnKey returns "suggest" only after a 300ms pause — no background threads
  for ($i = 32; $i -le 126; $i++) {
    $char = [char]$i
    if ($char -match '[a-zA-Z0-9\-\._/\\]') {
      Set-PSReadLineKeyHandler -Chord $char -ScriptBlock {
        param($key, $arg)
        $mode = _TacOnKey
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert($key.KeyChar)
        if ($mode -eq "paste") {
          _TacClearGhostText
        } elseif ($mode -eq "suggest") {
          Update-TacSuggestion
        }
        # "debounce" = do nothing extra, just insert
      }.GetNewClosure()
    }
  }

  # Space
  Set-PSReadLineKeyHandler -Chord ' ' -ScriptBlock {
    $mode = _TacOnKey
    [Microsoft.PowerShell.PSConsoleReadLine]::Insert(' ')
    if ($mode -eq "paste")   { _TacClearGhostText }
    elseif ($mode -eq "suggest") { Update-TacSuggestion }
  }

  # Ctrl+V — force paste window
  Set-PSReadLineKeyHandler -Chord 'Ctrl+v' -ScriptBlock {
    _TacClearGhostText
    $global:_TacPasteModeUntilMs = [System.DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds() + 400
    [Microsoft.PowerShell.PSConsoleReadLine]::Paste()
  }

  # Backspace
  Set-PSReadLineKeyHandler -Key Backspace -ScriptBlock {
    $mode = _TacOnKey
    if ($global:_TacSuggestionShown) {
      $line = $null; $cursor = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
      $actual = $line.Substring(0, $cursor)
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actual)
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($cursor)
      $global:_TacSuggestionShown = $false
    }
    [Microsoft.PowerShell.PSConsoleReadLine]::BackwardDeleteChar()
    if ($mode -eq "suggest") { Update-TacSuggestion }
    elseif ($mode -eq "paste") { _TacClearGhostText }
  }

  # Delete
  Set-PSReadLineKeyHandler -Key Delete -ScriptBlock {
    $mode = _TacOnKey
    if ($global:_TacSuggestionShown) {
      $line = $null; $cursor = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
      $actual = $line.Substring(0, $cursor)
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actual)
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($cursor)
      $global:_TacSuggestionShown = $false
    }
    [Microsoft.PowerShell.PSConsoleReadLine]::DeleteChar()
    if ($mode -eq "suggest") { Update-TacSuggestion }
    elseif ($mode -eq "paste") { _TacClearGhostText }
  }

  # Tab — accept suggestion or default tab complete
  Set-PSReadLineKeyHandler -Key Tab -ScriptBlock {
    if ($global:_TacCurrentSuggestion -and $global:_TacSuggestionShown) {
      try {
        $line = $null; $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        if ($line.Length -gt 0) {
          [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $global:_TacCurrentSuggestion)
        } else {
          [Microsoft.PowerShell.PSConsoleReadLine]::Insert($global:_TacCurrentSuggestion)
        }
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown   = $false
      } catch {
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown   = $false
        [Microsoft.PowerShell.PSConsoleReadLine]::TabCompleteNext()
      }
    } else {
      [Microsoft.PowerShell.PSConsoleReadLine]::TabCompleteNext()
    }
  }

  # Right arrow — accept suggestion or move cursor
  Set-PSReadLineKeyHandler -Key RightArrow -ScriptBlock {
    if ($global:_TacCurrentSuggestion -and $global:_TacSuggestionShown) {
      try {
        $line = $null; $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        if ($line.Length -gt 0) {
          [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $global:_TacCurrentSuggestion)
        } else {
          [Microsoft.PowerShell.PSConsoleReadLine]::Insert($global:_TacCurrentSuggestion)
        }
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown   = $false
      } catch {
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown   = $false
        [Microsoft.PowerShell.PSConsoleReadLine]::ForwardChar()
      }
    } else {
      [Microsoft.PowerShell.PSConsoleReadLine]::ForwardChar()
    }
  }

  # Escape — dismiss suggestion
  Set-PSReadLineKeyHandler -Key Escape -ScriptBlock {
    if ($global:_TacSuggestionShown) {
      try {
        $line = $null; $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        $actual = $line.Substring(0, $cursor)
        if ($line.Length -gt 0) {
          [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actual)
        }
        [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($actual.Length)
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown   = $false
      } catch {
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown   = $false
      }
    } else {
      [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
    }
  }
}

# ── Prompt hook: record executed commands ──────────────────────────────────
$null = New-Variable -Name _TacOriginalPrompt `
  -Value (Get-Item Function:\prompt -ErrorAction SilentlyContinue).ScriptBlock `
  -Scope Global -Force -ErrorAction SilentlyContinue

function global:prompt {
  $lastId = (Get-History -Count 1 -ErrorAction SilentlyContinue).Id
  if ($null -ne $lastId -and $lastId -ne $global:_TacLastRecordedId) {
    $global:_TacLastRecordedId = $lastId
    $lastCmd = (Get-History -Id $lastId -ErrorAction SilentlyContinue).CommandLine
    if ($lastCmd) {
      Start-Job -ScriptBlock {
        param($cmd)
        & tac --ipc record --buffer $cmd 2>$null
      } -ArgumentList $lastCmd | Out-Null
    }
  }
  if ($null -ne $global:_TacOriginalPrompt) {
    & $global:_TacOriginalPrompt
  } else {
    "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
  }
}
