/**
 * Shell hook snippet generation for bash, zsh, and PowerShell.
 *
 * The `init` CLI command outputs the appropriate snippet so the user can
 * source it in their shell configuration file.
 */

// ---------------------------------------------------------------------------
// Zsh hook snippet
// ---------------------------------------------------------------------------

export function getZshHook(): string {
  return `# terminalsense zsh hook
# Add this to your ~/.zshrc:
#   eval "$(terminalsense init zsh)"

_tac_preexec() {
  local result
  result=$(echo "$1" | timeout 0.1 terminalsense --ipc correct 2>/dev/null)
  if [[ -n "$result" ]]; then
    print -n "\\r\\033[K✓ autocorrected: $result\\n"
    eval "$result"
    return 1
  fi
}

_tac_zle_widget() {
  local full_suggestion ghost
  full_suggestion=$(echo "$BUFFER" | timeout 0.1 terminalsense --ipc suggest 2>/dev/null)
  if [[ -n "$full_suggestion" ]] && [[ "$full_suggestion" == "\${BUFFER}"* ]]; then
    ghost="\${full_suggestion:\${#BUFFER}}"
    if [[ -n "$ghost" ]]; then
      print -Pn "\\033[2m\${ghost}\\033[0m"
    fi
  fi
}

autoload -Uz add-zsh-hook
add-zsh-hook preexec _tac_preexec
zle -N _tac_zle_widget
bindkey '^I' _tac_zle_widget
`;
}

// ---------------------------------------------------------------------------
// Bash hook snippet
// ---------------------------------------------------------------------------

export function getBashHook(): string {
  return `# terminalsense bash hook
# Add this to your ~/.bashrc:
#   eval "$(terminalsense init bash)"

_tac_preexec() {
  local result
  result=$(echo "$1" | timeout 0.1 terminalsense --ipc correct 2>/dev/null)
  if [[ -n "$result" ]]; then
    echo -e "\\r\\033[K✓ autocorrected: $result"
    eval "$result"
    return 1
  fi
}

_tac_precmd() {
  local full_suggestion ghost
  full_suggestion=$(echo "$READLINE_LINE" | timeout 0.1 terminalsense --ipc suggest 2>/dev/null)
  if [[ -n "$full_suggestion" ]] && [[ "$full_suggestion" == "\${READLINE_LINE}"* ]]; then
    ghost="\${full_suggestion:\${#READLINE_LINE}}"
    if [[ -n "$ghost" ]]; then
      echo -ne "\\033[2m\${ghost}\\033[0m"
    fi
  fi
}

if declare -f preexec_functions > /dev/null 2>&1; then
  preexec_functions+=(_tac_preexec)
  precmd_functions+=(_tac_precmd)
else
  _tac_original_prompt_command="\${PROMPT_COMMAND}"
  PROMPT_COMMAND="_tac_precmd\${_tac_original_prompt_command:+; \${_tac_original_prompt_command}}"
  trap '_tac_preexec "\$BASH_COMMAND"' DEBUG
fi
`;
}

// ---------------------------------------------------------------------------
// PowerShell hook snippet (Windows)
// ---------------------------------------------------------------------------

export function getPowerShellHook(): string {
  return `# terminal-autocorrect PowerShell hook
# Generated by: tac init powershell
#
# INSTALLATION: Add this line to your $PROFILE:
#   . "C:\\path\\to\\tac-hook.ps1"

function _TacSend {
  param([string]$Type, [string]$Buffer)
  if ($global:_TacInHook) { return $null }
  try {
    $global:_TacInHook = $true
    $result = & tac --ipc $Type --buffer $Buffer 2>$null
    if ($result -is [array]) { return ($result -join '') }
    return $result
  } catch {
    return $null
  } finally {
    $global:_TacInHook = $false
  }
}

# State
$global:_TacInHook            = $false
$global:_TacCurrentSuggestion = $null
$global:_TacSuggestionShown   = $false

# Debounce: show suggestion only after 300ms pause in typing
# Paste burst: keys arriving < 8ms apart suppress suggestions for 300ms
$global:_TacLastKeyMs         = [long]0
$global:_TacDebounceMs        = 300
$global:_TacPasteModeUntilMs  = [long]0

function _TacOnKey {
  # Returns: "paste" | "debounce" | "suggest"
  $now = [System.DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
  $gap = $now - $global:_TacLastKeyMs
  $global:_TacLastKeyMs = $now
  if ($gap -ge 0 -and $gap -lt 8) {
    $global:_TacPasteModeUntilMs = $now + 300
  }
  if ($now -lt $global:_TacPasteModeUntilMs) { return "paste" }
  if ($gap -lt $global:_TacDebounceMs)        { return "debounce" }
  return "suggest"
}

function _TacClearGhostText {
  if ($global:_TacSuggestionShown) {
    $line = $null; $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    $actual = if ($line.Length -gt 0) { $line.Substring(0, $cursor) } else { "" }
    if ($line.Length -gt 0) {
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actual)
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($actual.Length)
    }
    $global:_TacSuggestionShown   = $false
    $global:_TacCurrentSuggestion = $null
  }
}

function Update-TacSuggestion {
  $line = $null; $cursor = $null
  [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
  $actual = if ($line.Length -gt 0) { $line.Substring(0, $cursor) } else { "" }
  if ($actual -and $actual.Trim().Length -gt 0) {
    $suggestion = _TacSend -Type 'suggest' -Buffer $actual.Trim()
    if ($suggestion -and $suggestion -ne $actual.Trim() -and $suggestion.StartsWith($actual.Trim())) {
      $ghost = $suggestion.Substring($actual.Trim().Length)
      if ($ghost) {
        if ($line.Length -gt 0) {
          [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actual + $ghost)
        } else {
          [Microsoft.PowerShell.PSConsoleReadLine]::Insert($actual + $ghost)
        }
        [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($actual.Length)
        $global:_TacCurrentSuggestion = $suggestion
        $global:_TacSuggestionShown   = $true
        return
      }
    }
  }
  if ($global:_TacSuggestionShown) {
    $line2 = $null; $cur2 = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line2, [ref]$cur2)
    $actual2 = if ($line2.Length -gt 0) { $line2.Substring(0, $cur2) } else { "" }
    if ($line2.Length -gt 0) {
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line2.Length, $actual2)
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($actual2.Length)
    }
  }
  $global:_TacCurrentSuggestion = $null
  $global:_TacSuggestionShown   = $false
}

function Learn-TypingPattern {
  param([string]$Command)
  if ($Command -and $Command.Length -gt 2) {
    for ($i = 1; $i -lt $Command.Length; $i++) {
      $prefix = $Command.Substring(0, $i)
      & tac --ipc learn --prefix $prefix --completion $Command 2>$null | Out-Null
    }
  }
}

if (Get-Module -ListAvailable -Name PSReadLine) {

  Set-PSReadLineKeyHandler -Key Enter -ScriptBlock {
    _TacClearGhostText
    $line = $null; $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    if ($line -and $line.Trim()) {
      $orig      = $line.Trim()
      $corrected = _TacSend -Type 'correct' -Buffer $orig
      if ($corrected -and $corrected -ne $orig -and $corrected.Trim()) {
        [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $corrected)
        Write-Host "\`nAutocorrected: $orig -> $corrected" -ForegroundColor Green
        Learn-TypingPattern -Command $corrected
      } else {
        Learn-TypingPattern -Command $orig
      }
    }
    $global:_TacCurrentSuggestion = $null
    $global:_TacSuggestionShown   = $false
    [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
  }

  for ($i = 32; $i -le 126; $i++) {
    $char = [char]$i
    if ($char -match '[a-zA-Z0-9\\-\\._/\\\\]') {
      Set-PSReadLineKeyHandler -Chord $char -ScriptBlock {
        param($key, $arg)
        $mode = _TacOnKey
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert($key.KeyChar)
        if ($mode -eq "paste")   { _TacClearGhostText }
        elseif ($mode -eq "suggest") { Update-TacSuggestion }
      }.GetNewClosure()
    }
  }

  Set-PSReadLineKeyHandler -Chord ' ' -ScriptBlock {
    $mode = _TacOnKey
    [Microsoft.PowerShell.PSConsoleReadLine]::Insert(' ')
    if ($mode -eq "paste")       { _TacClearGhostText }
    elseif ($mode -eq "suggest") { Update-TacSuggestion }
  }

  Set-PSReadLineKeyHandler -Chord 'Ctrl+v' -ScriptBlock {
    _TacClearGhostText
    $global:_TacPasteModeUntilMs = [System.DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds() + 400
    [Microsoft.PowerShell.PSConsoleReadLine]::Paste()
  }

  Set-PSReadLineKeyHandler -Key Backspace -ScriptBlock {
    $mode = _TacOnKey
    if ($global:_TacSuggestionShown) {
      $line = $null; $cursor = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
      $actual = $line.Substring(0, $cursor)
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actual)
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($cursor)
      $global:_TacSuggestionShown = $false
    }
    [Microsoft.PowerShell.PSConsoleReadLine]::BackwardDeleteChar()
    if ($mode -eq "suggest") { Update-TacSuggestion }
    elseif ($mode -eq "paste") { _TacClearGhostText }
  }

  Set-PSReadLineKeyHandler -Key Delete -ScriptBlock {
    $mode = _TacOnKey
    if ($global:_TacSuggestionShown) {
      $line = $null; $cursor = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
      $actual = $line.Substring(0, $cursor)
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actual)
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($cursor)
      $global:_TacSuggestionShown = $false
    }
    [Microsoft.PowerShell.PSConsoleReadLine]::DeleteChar()
    if ($mode -eq "suggest") { Update-TacSuggestion }
    elseif ($mode -eq "paste") { _TacClearGhostText }
  }

  Set-PSReadLineKeyHandler -Key Tab -ScriptBlock {
    if ($global:_TacCurrentSuggestion -and $global:_TacSuggestionShown) {
      try {
        $line = $null; $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        if ($line.Length -gt 0) {
          [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $global:_TacCurrentSuggestion)
        } else {
          [Microsoft.PowerShell.PSConsoleReadLine]::Insert($global:_TacCurrentSuggestion)
        }
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown   = $false
      } catch {
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown   = $false
        [Microsoft.PowerShell.PSConsoleReadLine]::TabCompleteNext()
      }
    } else {
      [Microsoft.PowerShell.PSConsoleReadLine]::TabCompleteNext()
    }
  }

  Set-PSReadLineKeyHandler -Key RightArrow -ScriptBlock {
    if ($global:_TacCurrentSuggestion -and $global:_TacSuggestionShown) {
      try {
        $line = $null; $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        if ($line.Length -gt 0) {
          [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $global:_TacCurrentSuggestion)
        } else {
          [Microsoft.PowerShell.PSConsoleReadLine]::Insert($global:_TacCurrentSuggestion)
        }
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown   = $false
      } catch {
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown   = $false
        [Microsoft.PowerShell.PSConsoleReadLine]::ForwardChar()
      }
    } else {
      [Microsoft.PowerShell.PSConsoleReadLine]::ForwardChar()
    }
  }

  Set-PSReadLineKeyHandler -Key Escape -ScriptBlock {
    if ($global:_TacSuggestionShown) {
      try {
        $line = $null; $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        $actual = $line.Substring(0, $cursor)
        if ($line.Length -gt 0) {
          [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $actual)
        }
        [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($actual.Length)
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown   = $false
      } catch {
        $global:_TacCurrentSuggestion = $null
        $global:_TacSuggestionShown   = $false
      }
    } else {
      [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
    }
  }
}

$null = New-Variable -Name _TacOriginalPrompt \`
  -Value (Get-Item Function:\\prompt -ErrorAction SilentlyContinue).ScriptBlock \`
  -Scope Global -Force -ErrorAction SilentlyContinue

function global:prompt {
  $lastId = (Get-History -Count 1 -ErrorAction SilentlyContinue).Id
  if ($null -ne $lastId -and $lastId -ne $global:_TacLastRecordedId) {
    $global:_TacLastRecordedId = $lastId
    $lastCmd = (Get-History -Id $lastId -ErrorAction SilentlyContinue).CommandLine
    if ($lastCmd) {
      Start-Job -ScriptBlock {
        param($cmd)
        & tac --ipc record --buffer $cmd 2>$null
      } -ArgumentList $lastCmd | Out-Null
    }
  }
  if ($null -ne $global:_TacOriginalPrompt) {
    & $global:_TacOriginalPrompt
  } else {
    "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
  }
}
`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function getShellHook(shell: "bash" | "zsh" | "powershell"): string {
  switch (shell) {
    case "zsh":
      return getZshHook();
    case "bash":
      return getBashHook();
    case "powershell":
      return getPowerShellHook();
    default: {
      const _exhaustive: never = shell;
      void _exhaustive;
      throw new Error(`Unsupported shell: ${String(shell)}. Supported shells: bash, zsh, powershell`);
    }
  }
}
